### ISSUE TITLE
Improve UXP of workflow form submission 

### ISSUE THREAD

**Issue by kmenzli** [exo-addons/bonita-extension#10]
currently, after submitting a workflow form, the following link displayed : 
"Your task has been taken into account"

It's not very user friendly. A few things should be done to improve it : 
* ask BD to provide a nice design for this message
* change the text to : "The form has been submitted. You will now be redirected to your previous page."
* redirect to the page from which the user was coming before he submited the form (home of it cannot be determined)

**Comment by rdenarie** [comment]
With 3.0.0, tasks are openend in Bonita Portal, which manage the page next to the form validation
