### ISSUE TITLE
Business Processes i18N

### ISSUE THREAD

**Issue by kmenzli** [exo-addons/bonita-extension#12]
Business processes do not seem translated.

When I switch to french, 
* In BPM gadget, I see : "Leave Application" > KO. It should be something like "Demande de Congé".
* in Application Submission form : everything remains in english

**Comment by rdenarie** [comment]
This issue is no more present with the version 3.0.0 of the application. Process and task are now displayed directly in Bonita Portal, which manage the display of the i18n
