### ISSUE TITLE
org.exoplatform.addons is not listed in the maven repository

### ISSUE THREAD

**Issue by Firexion** [exo-addons/bonita-extension#14]
Following the build instructions and when I reach the mvn clean install, receive the following error:

[ERROR]     Non-resolvable parent POM: Failure to find org.exoplatform.addons:ad
dons-parent-pom:pom:2 in http://repo.maven.apache.org/maven2 was cached in the l
ocal repository, resolution will not be reattempted until the update interval of
 central has elapsed or updates are forced and 'parent.relativePath' points at w
rong local POM @ line 8, column 10 -> [Help 2]

As far as I can tell, org.exoplatform.addons is not listed in the maven repository.  I was able to find several other exoplatform items listed there, but not addons.

**Comment by hristan** [comment]
Same issue here. Any workarounds?

**Comment by Lifestohack** [comment]
Same issue here.

**Comment by devrobot01** [comment]
I followed the workaround but still got errors !! 

[INFO] Error building POM (may not be this project's POM).

Project ID: org.exoplatform.addons.bonita:bonita-extension:pom:2.0.1

Reason: Cannot find parent: org.exoplatform.addons:addons-parent-pom for project: org.exoplatform.addons.bonita:bonita-extension:pom:2.0.1 for project org.exoplatform.addons.bonita:bonita-extension:pom:2.0.1


[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Cannot find parent: org.exoplatform.addons:addons-parent-pom for project: org.exoplatform.addons.bonita:bonita-extension:pom:2.0.1 for project org.exoplatform.addons.bonita:bonita-extension:pom:2.0.1
        at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:404)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:272)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by devrobot01** [comment]
ok got it :)
download the 
addons-parent-pom-2-source-release.zip
addons-parent-pom-2.pom
from https://repository.exoplatform.org/public/org/exoplatform/addons/addons-parent-pom/2/
and copy it into ~/.m2/repository/org/exoplatform/addons/addons-parent-pom/2$
i am using ubuntu

**Comment by rdenarie** [comment]
Hello,

Which version of the eXo do you use.
I just update the addon for PLF 4.3.0

**Comment by devrobot01** [comment]
i am using 4.3.0

**Comment by rdenarie** [comment]
Hello,

So try to use the version 3.0.0 of the addon, coming from the addon catalog. It should work better.

I close this issue then.
Thanks
