### ISSUE TITLE
Tasks and processes are listed twice

### ISSUE THREAD

**Issue by pozil** [exo-addons/bonita-extension#17]
Hi,

I just tried to use the extension following your instructions and the extension did connect to Bonita.
However, all tasks and process are listed twice the portlet:
![duplicated_tasks_and_processes](http://s17.postimg.org/5qtw0ndu7/duplicated_tasks_and_processes.png)

Here is my environment:
- eXoPlatform community 4.3.0
- bonita-extension v3.0.0 in non SSO mode
- Bonita BPM community 7.2

Let me know if you need more information to address the issue.

Cheers,

**Comment by rdenarie** [comment]
Hello Philip.
Have you some logs in eXo console ?
In your browser network console, how many request to get process and task can you see ?
In Bonita Portal, can you see only one task and one process ?

Thanks for your answers.

**Comment by rdenarie** [comment]
Have you only one portlet of Bonita Tasks on your page ? or 2 ?

**Comment by pozil** [comment]
Hi Romain,

I have only one portlet configured on the intranet home page.

Looking at Chrome developer console, there are REST calls to the service.
These have the proper returns values (only one process and one task) however the calls are repeated.
Eg, for a single page load I have these duplicated requests:
```
http://localhost:8080/rest/bonitaService/getTasks
http://localhost:8080/rest/bonitaService/getProcess
http://localhost:8080/rest/bonitaService/getTasks
http://localhost:8080/rest/bonitaService/getProcess
```

I have not seen any problematic logs in
`platform-community-4.3.0/logs/platform.log`

Cheers,

**Comment by rdenarie** [comment]
Did you add the bonita Portlet on the home page manually ? Or the portlet was here at startup ?
In fact, the only way I managed to reproduce your problem was to add a second bonita portlet on the same page.

**Comment by pozil** [comment]
Sorry but I just realized that you are right: the issue occurs because the portlet is added twice.
The strange thing however is that I only added it once on the page but it appears twice.

Here is the page layout where I added the portlet myself:
![](http://s9.postimg.org/3uol7oopr/page_layout.png)

Here is the same page at runtime (I did not add the portlet on the right column):
![](http://s8.postimg.org/5utydp8bp/rendered_page.png)

**Comment by rdenarie** [comment]
It is not strange :)

In fact, for help users, the portlet is added automatically  in dynamic container on top right column. This is done by configuration in the extension.
So you don't need to go on Application page, add the portlet in a category, set rights, add the portlet on page ... This portlet is already on the page. 

So remove, the portlet in the center of your page, and only one task and one process will appear on the portlet on top right column.

Regards

**Comment by pozil** [comment]
Ok, thanks a lot for you help.
