### ISSUE TITLE
Link to Bonita forms is broken

### ISSUE THREAD

**Issue by pozil** [exo-addons/bonita-extension#18]
Hi,

When clicking on a task in the portlet there is a redirection error and I end up on this invalid URL:
`http://bonita/login.jsp?redirectUrl=%2F%2Fbonita%2Fportal%2Fhomepage#?id=2&_p=performTask&_pf=1`

The problem seems to be related to the URL of the task link:
`http://localhost:48165//bonita/portal/homepage#?id=2&_p=performTask&_pf=1`

Notice that there are 2 forward slashes before the application name (bonita).
If I remove one of them, then the URL is correct and the task's form is correctly displayed.

This is rather strange as I configured this properly in `exo.properties`:
`bonita.server.url=http://localhost:48165/bonita`

Here is my environment:
- eXoPlatform community 4.3.0
- bonita-extension v3.0.0 in non SSO mode
- Bonita BPM community 7.2

Let me know if you need more information to address the issue.

Cheers,

**Comment by rdenarie** [comment]
Hum, I thihnk you should not add the application context in the url.
Try to configure this :
bonita.server.url=http://localhost:48165

**Comment by pozil** [comment]
Ok, I just followed instructions here but it was not clear:
https://github.com/exo-addons/bonita-extension/wiki/Non-SSO-Mode

I retried without the application context and now the link works fine.

Thanks for your help on that.

**Comment by rdenarie** [comment]
I  repopen the issue to remind to better catch wrong format in url to prevent problem like your.

**Comment by rdenarie** [comment]
Update in develop branch to check bonita url. Now it should work with url like this :
bonita.server.url=http://localhost:48165/bonita

I close the issue.
