### ISSUE TITLE
BonitaXP page (Content not displayed)

### ISSUE THREAD

**Issue by heycarlost** [exo-addons/bonita-extension#5]
Hi, I'm using bonita-extension, and I have a problem with BonitaXP page. I followed all the steps, and used the indicated versions in Readme.md.
I can enter to this page, but the content is not displayed.
In the source code i see this: <iframe src="null/bonita"></iframe>
Thanks in advance.

![Error_bonita_eXo](https://f.cloud.github.com/assets/3332175/84217/2ec65fb8-6405-11e2-8523-066201c40ca5.jpg)
![Error_bonita_eXo_code](https://f.cloud.github.com/assets/3332175/84218/32b1b94c-6405-11e2-9c18-9a782a672729.jpg)

**Comment by rdenarie** [comment]
Try  the last version of the addon 3.0.0, which works on PLF 4.3.0.
The management of tasks and process is different and should resolve your problem
